/**
 * What the roles and skills pickers offer, tagged by domain.
 *
 * Seed text, not an enum: both columns are free-form `text[]` and the extractor
 * returns whatever the CV said. The picker offers these; it never restricts to
 * them, and anything typed is still added.
 *
 * Grouped into sections because a flat list in declaration order shows everyone the
 * same first rows. A backend CV was being offered "Digital Marketing Specialist" and "Adobe
 * Photoshop" before anything adjacent to Go. `rankSuggestions` fixes the ordering
 * by matching against what the CV already produced.
 *
 * `general` marks the genuinely cross-domain entries. They rank between a match
 * and a miss so a marketing CV still sees "Project Management", and so a CV whose
 * domain we could not read still gets a sensible list rather than an arbitrary one.
 *
 * Kept out of `steps.ts` deliberately: that module is imported by `gate.ts` and so
 * reaches the proxy on every request, and this is a lot of string data to carry
 * into a middleware bundle for no reason.
 */

/**
 * One per industry the role list actually covers.
 *
 * Granular on purpose. Folding aviation into ops, or healthcare into general,
 * would put a cardiologist and a Kubernetes engineer in the same bucket and rank
 * nothing useful for either. The cost of a domain is one string in a tag; the cost
 * of collapsing two is a picker that offers the wrong profession first.
 */
export type Domain =
  | 'software'
  | 'ai'
  | 'data'
  | 'design'
  | 'product'
  | 'sales'
  | 'marketing'
  | 'success'
  | 'business'
  | 'ops'
  | 'supply'
  | 'manufacturing'
  | 'finance'
  | 'people'
  | 'legal'
  | 'security'
  | 'it'
  | 'healthcare'
  | 'education'
  | 'media'
  | 'construction'
  | 'hospitality'
  | 'retail'
  | 'government'
  | 'energy'
  | 'agriculture'
  | 'aviation'
  | 'maritime'
  | 'executive'
  | 'startup'
  | 'general'

export type Section = {
  /** The header shown above the group in the picker. */
  label: string
  /**
   * Every domain the section touches, so a chip from any of them ranks the whole
   * section up. Sections ARE domains: one section per domain keeps ranking and
   * grouping the same idea rather than two that can drift apart.
   */
  domains: readonly Domain[]
  items: readonly string[]
}

/**
 * Cross-industry leads, because that is what an unreadable CV gets offered when
 * `rankSections` has nothing to rank by. Everything after it is reordered per user.
 */
export const ROLE_SECTIONS: readonly Section[] = [
  {
    label: 'Cross-industry',
    domains: ['general'],
    items: [
      'Product Manager',
      'Project Manager',
      'Program Manager',
      'Business Analyst',
      'Consultant',
      'Chief of Staff',
      'Legal Counsel',
    ],
  },
  {
    label: 'Software engineering',
    // `ops` is earned — DevOps Engineer, Site Reliability Engineer, Platform
    // Engineer and Linux Engineer all sit here. `people` was not: Engineering
    // Manager and Director of Engineering are engineering leadership, and an HR
    // CV has no business being offered Backend Engineer.
    domains: ['ops', 'software'],
    items: [
      'Software Engineer',
      'Backend Engineer',
      'Frontend Engineer',
      'Full Stack Engineer',
      'Mobile Engineer',
      'Android Engineer',
      'iOS Engineer',
      'QA Engineer',
      'Test Automation Engineer',
      'DevOps Engineer',
      'Site Reliability Engineer',
      'Platform Engineer',
      'Security Engineer',
      'Engineering Manager',
      'Tech Lead',
      'Solutions Architect',
      'Technical Writer',
      'Junior Software Engineer',
      'Mid-Level Software Engineer',
      'Senior Software Engineer',
      'Staff Software Engineer',
      'Principal Software Engineer',
      'Distinguished Engineer',
      'Director of Engineering',
      'VP of Engineering',
      'Head of Engineering',
      'API Engineer',
      'Integration Engineer',
      'Middleware Engineer',
      'Distributed Systems Engineer',
      'Compiler Engineer',
      'Kernel Engineer',
      'Linux Engineer',
      'Windows Systems Engineer',
      'macOS Engineer',
      'Graphics Engineer',
      'Rendering Engineer',
      'Game Engine Developer',
      'Simulation Engineer',
      'Search Engineer',
      'GIS Developer',
      'ERP Developer',
      'SAP Developer',
      'Salesforce Developer',
      'Dynamics 365 Developer',
      'Odoo Developer',
      'WordPress Developer',
      'Shopify Developer',
      'Magento Developer',
      'Salesforce Architect',
      'CRM Developer',
      'Low-Code Developer',
      'No-Code Developer',
    ],
  },
  {
    label: 'AI and machine learning',
    domains: ['ai', 'software'],
    items: [
      'Computer Vision Engineer',
      'NLP Engineer',
      'Generative AI Engineer',
      'LLM Engineer',
      'Prompt Engineer',
      'AI Platform Engineer',
      'Recommendation Systems Engineer',
      'AI Product Manager',
      'AI Solutions Architect',
      'AI Consultant',
      'AI Ethics Specialist',
      'AI Trainer',
      'AI Annotator',
      'AI Operations Engineer',
      'Prompt Designer',
      'Conversational AI Engineer',
      'Chatbot Developer',
      'Robotics Software Engineer',
      'Autonomous Systems Engineer',
    ],
  },
  {
    label: 'Data',
    domains: ['data', 'software'],
    items: [
      'Data Analyst',
      'Data Engineer',
      'Data Scientist',
      'Analytics Engineer',
      'Machine Learning Engineer',
      'Business Intelligence Analyst',
      'Research Scientist',
      'Data Platform Engineer',
      'Storage Engineer',
      'Data Visualization Specialist',
      'Data Quality Analyst',
      'Data Migration Specialist',
      'ETL Developer',
      'BI Developer',
      'Reporting Analyst',
      'Database Engineer',
      'SQL Developer',
      'NoSQL Database Engineer',
      'Big Data Engineer',
      'Hadoop Engineer',
      'Spark Engineer',
      'Snowflake Engineer',
      'Databricks Engineer',
      'Data Warehouse Architect',
      'Master Data Specialist',
    ],
  },
  {
    label: 'Design',
    // "Design Manager" and "Design Lead" are design leadership, not HR. Nothing
    // in this section belongs to someone whose domain is people.
    domains: ['design'],
    items: [
      'Product Designer',
      'UX Designer',
      'UI Designer',
      'UX Researcher',
      'Graphic Designer',
      'Design Lead',
      'Motion Designer',
      'Senior Product Designer',
      'Design Manager',
      'Creative Designer',
      'Experience Designer',
      'Accessibility Designer',
      'Accessibility Specialist',
      'Information Architect',
      'Content Designer',
      'UX Writer',
      'UX Content Strategist',
      'Design Technologist',
      'Visual Communication Designer',
    ],
  },
  {
    label: 'Product',
    domains: ['product'],
    items: [
      'Associate Product Manager',
      'Product Analyst',
      'Product Strategist',
      'Product Marketing Lead',
      'Product Growth Lead',
      'Head of Product',
      'VP Product',
      'Chief Product Officer',
      'Product Innovation Manager',
      'Product Operations Specialist',
    ],
  },
  {
    label: 'Sales',
    // Not `people`. Sales is not an HR discipline, and while `domains` is only
    // relatedness now, the tag still says "offer these to an HR user" — which is
    // wrong on its own terms, and was what put Software Engineer above Sales for
    // a business-development CV back when this list doubled as evidence.
    domains: ['sales'],
    items: [
      'Account Executive',
      'Sales Executive',
      'Sales Manager',
      'Business Development Manager',
      'Sales Development Representative',
      'Partnerships Manager',
      'Account Manager',
      'Sales Consultant',
      'Retail Sales Associate',
      'Enterprise Sales Manager',
      'Regional Sales Manager',
      'Area Sales Manager',
      'Sales Operations Analyst',
      'Sales Enablement Manager',
      'Sales Trainer',
      'Customer Acquisition Specialist',
      'Lead Generation Specialist',
      'Pre-Sales Engineer',
      'Technical Sales Specialist',
      'Commercial Manager',
      'Commercial Director',
      'Revenue Operations Manager',
    ],
  },
  {
    label: 'Marketing',
    domains: ['data', 'marketing'],
    items: [
      'Marketing Manager',
      'Digital Marketing Specialist',
      'Content Strategist',
      'SEO Specialist',
      'Social Media Manager',
      'Brand Manager',
      'Growth Manager',
      'Performance Marketing Manager',
      'Marketing Coordinator',
      'Marketing Executive',
      'Marketing Communications Manager',
      'Communications Specialist',
      'Public Relations Manager',
      'Corporate Communications Manager',
      'Demand Generation Manager',
      'Campaign Manager',
      'Acquisition Marketing Specialist',
      'Lifecycle Marketing Manager',
      'Affiliate Marketing Manager',
      'Influencer Marketing Manager',
      'E-commerce Marketing Specialist',
      'Marketplace Specialist',
      'Paid Media Specialist',
      'Display Advertising Specialist',
      'Media Planner',
      'Brand Strategist',
      'Consumer Insights Analyst',
      'Creative Strategist',
      'Video Content Producer',
      'Podcast Producer',
      'SEO Content Strategist',
    ],
  },
  {
    label: 'Customer success',
    domains: ['success'],
    items: [
      'Enterprise Customer Success Manager',
      'Customer Success Director',
      'Customer Success Operations Manager',
      'Customer Success Engineer',
      'Customer Education Manager',
      'Customer Advocate',
      'Customer Retention Specialist',
      'Technical Consultant',
      'Implementation Engineer',
      'Support Team Lead',
      'Support Manager',
      'Escalation Engineer',
      'Service Delivery Manager',
    ],
  },
  {
    label: 'Business and strategy',
    domains: ['business'],
    items: [
      'Operations Analyst',
      'Revenue Analyst',
      'Pricing Analyst',
      'Market Research Analyst',
      'Business Intelligence Manager',
      'Corporate Strategy Manager',
      'Chief Strategy Officer',
      'Business Process Analyst',
      'Business Transformation Manager',
      'Change Manager',
      'Continuous Improvement Manager',
    ],
  },
  {
    label: 'Operations and infrastructure',
    domains: ['data', 'finance', 'ops', 'sales', 'software'],
    items: [
      'Operations Manager',
      'Customer Success Manager',
      'Customer Support Specialist',
      'Supply Chain Analyst',
      'Logistics Coordinator',
      'Procurement Specialist',
      'Quality Assurance Manager',
      'AWS Cloud Engineer',
      'Azure Cloud Engineer',
      'Google Cloud Engineer',
      'Kubernetes Engineer',
      'Docker Engineer',
      'Virtualization Engineer',
      'Observability Engineer',
      'Reliability Engineer',
      'Infrastructure Automation Engineer',
      'FinOps Engineer',
      'Platform Reliability Engineer',
      'Systems Reliability Engineer',
    ],
  },
  {
    label: 'Supply chain and logistics',
    domains: ['supply'],
    items: [
      'Supply Chain Director',
      'Procurement Manager',
      'Strategic Sourcing Specialist',
      'Purchasing Officer',
      'Purchasing Manager',
      'Demand Planner',
      'Supply Planner',
      'Logistics Analyst',
      'Logistics Manager',
      'Fleet Manager',
      'Transportation Coordinator',
      'Export Specialist',
      'Import Specialist',
      'Customs Broker',
    ],
  },
  {
    label: 'Manufacturing',
    domains: ['manufacturing'],
    items: [
      'Lean Manufacturing Engineer',
      'Automation Engineer',
      'PLC Programmer',
      'CNC Programmer',
      'Tooling Engineer',
      'Production Planner',
      'Plant Manager',
      'Factory Manager',
      'Manufacturing Supervisor',
      'Production Operator',
      'Machine Operator',
    ],
  },
  {
    label: 'Finance',
    domains: ['finance'],
    items: [
      'Financial Analyst',
      'Accountant',
      'Auditor',
      'Controller',
      'Investment Analyst',
      'Tax Specialist',
      'Accounts Payable Specialist',
      'Accounts Receivable Specialist',
      'Payroll Specialist',
      'Bookkeeper',
      'Cost Accountant',
      'Budget Analyst',
      'FP&A Analyst',
      'Corporate Finance Manager',
      'Finance Business Partner',
      'Investment Manager',
      'Wealth Manager',
      'Portfolio Manager',
      'Equity Research Analyst',
      'Credit Analyst',
      'Actuary',
      'Internal Auditor',
      'External Auditor',
      'Forensic Accountant',
    ],
  },
  {
    label: 'People and HR',
    domains: ['ops', 'people'],
    items: [
      'Human Resources Manager',
      'Recruiter',
      'Talent Acquisition Specialist',
      'People Operations Specialist',
      'Learning and Development Manager',
      'HR Coordinator',
      'HR Administrator',
      'HR Director',
      'Chief Human Resources Officer',
      'Employer Branding Specialist',
      'Talent Management Specialist',
      'Organizational Development Specialist',
      'Employee Relations Specialist',
      'HRIS Analyst',
      'Workforce Planning Analyst',
      'Recruitment Coordinator',
      'Campus Recruiter',
      'Executive Recruiter',
    ],
  },
  {
    label: 'Legal and compliance',
    domains: ['legal'],
    items: [
      'Corporate Lawyer',
      'Litigation Lawyer',
      'Intellectual Property Lawyer',
      'Patent Attorney',
      'Legal Operations Manager',
      'Paralegal',
      'Compliance Manager',
      'Anti-Money Laundering Analyst',
      'Regulatory Affairs Specialist',
      'Governance Specialist',
    ],
  },
  {
    label: 'Security',
    domains: ['ops', 'security'],
    items: [
      'Cloud Security Engineer',
      'DevSecOps Engineer',
      'Chief Information Security Officer',
      'Security Operations Manager',
      'Digital Forensics Analyst',
      'Malware Analyst',
      'Red Team Operator',
      'Blue Team Analyst',
      'Purple Team Engineer',
      'Vulnerability Management Specialist',
      'Application Security Engineer',
      'Cloud Security Architect',
      'Security Auditor',
    ],
  },
  {
    label: 'IT and support',
    domains: ['it', 'software'],
    items: [
      'Networking Engineer',
      'Telecom Engineer',
      'VoIP Engineer',
      'Network Administrator',
      'Desktop Support Technician',
      'Field Support Engineer',
      'Technical Specialist',
      'IT Operations Manager',
      'Enterprise Architect',
      'Enterprise Systems Administrator',
      'Storage Administrator',
      'Backup Administrator',
      'Messaging Administrator',
      'Exchange Administrator',
      'SCCM Administrator',
      'Endpoint Engineer',
    ],
  },
  {
    label: 'Healthcare',
    domains: ['healthcare'],
    items: [
      'Surgeon',
      'Pediatrician',
      'Cardiologist',
      'Dermatologist',
      'Emergency Physician',
      'Anesthesiologist',
      'Midwife',
      'Occupational Therapist',
      'Speech Therapist',
      'Veterinary Doctor',
      'Medical Coder',
      'Clinical Research Associate',
      'Healthcare Administrator',
    ],
  },
  {
    label: 'Education',
    domains: ['education'],
    items: [
      'School Principal',
      'Vice Principal',
      'Dean',
      'Education Consultant',
      'Academic Coordinator',
      'School Counselor',
      'Student Success Advisor',
      'Instructional Coach',
      'Online Course Creator',
      'E-learning Specialist',
    ],
  },
  {
    label: 'Media and creative',
    domains: ['media'],
    items: [
      'Film Director',
      'Screenwriter',
      'Producer',
      'Broadcast Engineer',
      'News Editor',
      'Journalist',
      'News Anchor',
      'Radio Host',
      'Sound Engineer',
      'Audio Engineer',
      'Colorist',
      'VFX Artist',
      'Character Artist',
      'Environment Artist',
      'Technical Artist',
      'UI Artist',
      'Concept Artist',
    ],
  },
  {
    label: 'Construction and engineering',
    domains: ['construction'],
    items: [
      'Project Engineer',
      'Building Inspector',
      'Surveyor',
      'Urban Designer',
      'Landscape Architect',
      'Environmental Engineer',
      'Geotechnical Engineer',
      'HVAC Engineer',
      'Fire Protection Engineer',
      'BIM Engineer',
    ],
  },
  {
    label: 'Hospitality and travel',
    domains: ['hospitality'],
    items: [
      'Resort Manager',
      'Travel Consultant',
      'Tour Guide',
      'Concierge',
      'Cruise Director',
      'Cabin Crew',
      'Flight Attendant',
      'Airline Operations Officer',
      'Hotel General Manager',
    ],
  },
  {
    label: 'Retail and e-commerce',
    domains: ['retail'],
    items: [
      'E-commerce Manager',
      'Category Analyst',
      'Pricing Manager',
      'Visual Merchandiser',
      'Inventory Analyst',
      'Store Supervisor',
      'Warehouse Associate',
      'Fulfillment Specialist',
      'Personal Shopper',
    ],
  },
  {
    label: 'Government and public sector',
    domains: ['government'],
    items: [
      'Foreign Affairs Officer',
      'Diplomat',
      'Intelligence Analyst',
      'Public Health Officer',
      'Disaster Management Officer',
      'Environmental Officer',
      'Tax Officer',
      'Customs Officer',
    ],
  },
  {
    label: 'Energy',
    domains: ['energy'],
    items: [
      'Petroleum Engineer',
      'Mining Engineer',
      'Renewable Energy Engineer',
      'Solar Engineer',
      'Wind Energy Engineer',
      'Power Systems Engineer',
      'Electrical Grid Engineer',
      'Nuclear Engineer',
    ],
  },
  {
    label: 'Agriculture and food',
    domains: ['agriculture'],
    items: [
      'Agronomist',
      'Agricultural Engineer',
      'Farm Manager',
      'Livestock Manager',
      'Fisheries Officer',
      'Aquaculture Specialist',
      'Food Scientist',
      'Food Technologist',
    ],
  },
  {
    label: 'Aviation',
    domains: ['aviation'],
    items: [
      'Airline Pilot',
      'Commercial Pilot',
      'Air Traffic Controller',
      'Aircraft Maintenance Engineer',
      'Avionics Technician',
      'Flight Operations Manager',
    ],
  },
  {
    label: 'Maritime',
    domains: ['maritime'],
    items: [
      'Ship Captain',
      'Marine Engineer',
      'Naval Architect',
      'Port Manager',
      'Deck Officer',
      'Marine Surveyor',
    ],
  },
  {
    label: 'Executive',
    domains: ['executive'],
    items: [
      'President',
      'Managing Director',
      'General Manager',
      'Executive Director',
      'Board Member',
      'Board Advisor',
      'Chairman',
      'Chief Revenue Officer',
      'Chief Growth Officer',
      'Chief Information Officer',
      'Chief Data Officer',
      'Chief AI Officer',
    ],
  },
  {
    label: 'Startup and investing',
    domains: ['startup'],
    items: [
      'Founder',
      'Co-Founder',
      'Founding Engineer',
      'Founding Designer',
      'Founding Product Manager',
      // Abbreviation carried in the label rather than as a second entry: search
      // is a substring match over the whole list, so "EIR" finds this row and
      // "Entrepreneur" still does too. A separate 'EIR' item would be a second
      // row meaning the same thing, which the no-duplicates test exists to stop.
      'Entrepreneur in Residence (EIR)',
      'Venture Partner',
      'Startup Advisor',
      'Angel Investor',
      'Venture Capital Associate',
      'Venture Capital Principal',
      'Venture Capital Partner',
    ],
  },
]

export const SKILL_SECTIONS: readonly Section[] = [
  {
    label: 'Cross-industry',
    domains: ['general'],
    items: [
      'Communication',
      'Problem Solving',
      'Leadership',
      'Project Management',
      'Stakeholder Management',
      'Public Speaking',
      'Agile',
      'Scrum',
      'Excel',
      'Data Analysis',
      'Jira',
      'Notion',
    ],
  },
  {
    label: 'Software engineering',
    domains: ['data', 'ops', 'software'],
    items: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Go',
      'Java',
      'Kotlin',
      'Swift',
      'PHP',
      'Ruby',
      'Rust',
      'C#',
      'React',
      'Next.js',
      'Vue.js',
      'Node.js',
      'Django',
      'Laravel',
      'Spring Boot',
      'React Native',
      'Flutter',
      'REST APIs',
      'GraphQL',
      'gRPC',
      'Git',
      'Docker',
      'Kubernetes',
      'Terraform',
      'CI/CD',
      'Linux',
      'AWS',
      'Google Cloud',
      'Azure',
      'Prometheus',
      'Redis',
      'Kafka',
      'Unit Testing',
      'Playwright',
    ],
  },
  {
    label: 'Data',
    domains: ['data', 'finance', 'marketing', 'software'],
    items: [
      'SQL',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'BigQuery',
      'Snowflake',
      'dbt',
      'Airflow',
      'Spark',
      'Pandas',
      'Power BI',
      'Tableau',
      'Looker',
      'Machine Learning',
      'Statistics',
      'A/B Testing',
      'Data Visualisation',
    ],
  },
  {
    label: 'Design',
    domains: ['design', 'software'],
    items: [
      'Figma',
      'Sketch',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Adobe XD',
      'Prototyping',
      'Wireframing',
      'Design Systems',
      'UX Research',
      'Usability Testing',
      'Accessibility',
    ],
  },
  {
    label: 'Sales',
    domains: ['marketing', 'sales'],
    items: [
      'B2B Sales',
      'Lead Generation',
      'Negotiation',
      'Salesforce',
      'HubSpot',
      'Pipeline Management',
      'Cold Outreach',
    ],
  },
  {
    label: 'Marketing',
    domains: ['data', 'marketing'],
    items: [
      'SEO',
      'SEM',
      'Content Marketing',
      'Copywriting',
      'Email Marketing',
      'Google Analytics',
      'Google Ads',
      'Meta Ads Manager',
      'Social Media Marketing',
      'Brand Strategy',
      'Marketing Automation',
    ],
  },
  {
    label: 'Operations and infrastructure',
    domains: ['ops'],
    items: [
      'Supply Chain Management',
      'Inventory Management',
      'Process Improvement',
      'Vendor Management',
      'Customer Experience Management',
      'Zendesk',
    ],
  },
  {
    label: 'Finance',
    domains: ['data', 'finance'],
    items: [
      'Financial Modelling',
      'Financial Reporting',
      'Budgeting',
      'Forecasting',
      'Accounting',
      'Bloomberg Terminal',
      'VBA',
      'Risk Management',
    ],
  },
  {
    label: 'People and HR',
    domains: ['people'],
    items: [
      'Recruiting',
      'Interviewing',
      'Onboarding',
      'Performance Management',
      'Coaching',
    ],
  },
  {
    label: 'Programming languages',
    domains: ['software'],
    items: [
      'Zig',
      'Nim',
      'Crystal',
      'OCaml',
      'F#',
      'Erlang',
      'Solidity',
      'VHDL',
      'Verilog',
      'Assembly',
      'Apex',
      'ABAP',
      'Tcl',
      'Visual Basic .NET',
    ],
  },
  {
    label: 'Backend frameworks',
    domains: ['software'],
    items: [
      'Koa.js',
      'Hapi.js',
      'AdonisJS',
      'FeathersJS',
      'Meteor',
      'Quarkus',
      'Micronaut',
      'Dropwizard',
      'Vert.x',
      'Akka',
      'Play Framework',
      'Strapi',
      'Directus',
      'Hasura',
      'Supabase',
      'Parse Server',
    ],
  },
  {
    label: 'Frontend technologies',
    domains: ['software'],
    items: [
      'Alpine.js',
      'SolidJS',
      'Lit',
      'Preact',
      'Qwik',
      'HTMX',
      'Stimulus',
      'Emotion',
      'Styled Components',
      'CSS Modules',
      'PostCSS',
      'Framer Motion',
      'GSAP',
      'Three.js',
      'Babylon.js',
      'D3.js',
      'Chart.js',
      'Highcharts',
      'ECharts',
    ],
  },
  {
    label: 'APIs and integration',
    domains: ['software'],
    items: [
      'OpenAPI',
      'Swagger',
      'API Gateway',
      'API Security',
      'API Versioning',
      'Webhooks',
      'OAuth 2.0',
      'OpenID Connect',
      'SAML',
      'SOAP',
      'JSON',
      'XML',
      'YAML',
      'AsyncAPI',
    ],
  },
  {
    label: 'Authentication and security',
    domains: ['security'],
    items: [
      'JWT',
      'MFA',
      'Single Sign-On',
      'Identity Federation',
      'LDAP',
      'Active Directory',
      'Keycloak',
      'Auth0',
      'Okta',
      'Azure AD',
      'Secrets Management',
      'HashiCorp Vault',
    ],
  },
  {
    label: 'Databases',
    domains: ['data'],
    items: [
      'CockroachDB',
      'YugabyteDB',
      'TiDB',
      'Amazon Aurora',
      'Azure Cosmos DB',
      'Amazon Redshift',
      'Greenplum',
      'Apache Hive',
      'Apache HBase',
      'DuckDB',
      'Realm',
      'LiteFS',
    ],
  },
  {
    label: 'Messaging and streaming',
    domains: ['software'],
    items: [
      'RabbitMQ',
      'ActiveMQ',
      'NATS',
      'Apache Pulsar',
      'Amazon SQS',
      'Amazon SNS',
      'Google Pub/Sub',
      'Azure Service Bus',
      'Redis Streams',
      'EventBridge',
    ],
  },
  {
    label: 'DevOps',
    domains: ['ops'],
    items: [
      'OpenShift',
      'Rancher',
      'Podman',
      'Nomad',
      'Consul',
      'Istio',
      'Linkerd',
      'Envoy',
      'Grafana',
      'Loki',
      'Jaeger',
      'OpenTelemetry',
      'Fluentd',
      'Logstash',
      'Kibana',
    ],
  },
  {
    label: 'Infrastructure',
    domains: ['it'],
    items: [
      'Virtual Machines',
      'VMware',
      'Hyper-V',
      'Proxmox',
      'Bare Metal Deployment',
      'High Availability',
      'Disaster Recovery',
      'Capacity Planning',
      'Infrastructure Monitoring',
    ],
  },
  {
    label: 'Amazon Web Services',
    domains: ['ops'],
    items: [
      'EC2',
      'ECS',
      'EKS',
      'Lambda',
      'S3',
      'RDS',
      'DynamoDB',
      'CloudFront',
      'Route 53',
      'IAM',
      'CloudWatch',
      'CloudFormation',
    ],
  },
  {
    label: 'Microsoft Azure',
    domains: ['ops'],
    items: [
      'Azure Functions',
      'Azure Kubernetes Service',
      'Azure SQL Database',
      'Azure Blob Storage',
      'Azure DevOps',
      'Azure Monitor',
      'Azure Active Directory',
    ],
  },
  {
    label: 'Google Cloud',
    domains: ['ops'],
    items: [
      'Cloud Run',
      'Cloud Functions',
      'Cloud SQL',
      'Bigtable',
      'Cloud Storage',
      'Cloud Build',
      'Vertex AI',
      'Memorystore',
      'Pub/Sub',
    ],
  },
  {
    label: 'AI and machine learning',
    domains: ['ai'],
    items: [
      'AI Model Evaluation',
      'AI Safety',
      'AI Governance',
      'Fine-tuning LLMs',
      'Embeddings',
      'Vector Databases',
      'Semantic Search',
      'Prompt Optimization',
      'Prompt Chaining',
      'AI Workflow Design',
      'AI Automation',
      'AI Orchestration',
      'AI Evaluation Frameworks',
    ],
  },
  {
    label: 'Vector databases',
    domains: ['ai'],
    items: [
      'Pinecone',
      'Weaviate',
      'Milvus',
      'ChromaDB',
      'Qdrant',
      'pgvector',
      'Vespa',
    ],
  },
  {
    label: 'AI frameworks',
    domains: ['ai'],
    items: [
      'OpenAI API',
      'Anthropic API',
      'Gemini API',
      'Ollama',
      'vLLM',
      'LangGraph',
      'DSPy',
      'AutoGen',
      'CrewAI',
      'Haystack',
      'Semantic Kernel',
    ],
  },
  {
    label: 'Data engineering',
    domains: ['data'],
    items: [
      'Apache Beam',
      'Apache Flink',
      'Delta Lake',
      'Iceberg',
      'Apache NiFi',
      'Talend',
      'Informatica',
      'Fivetran',
      'Airbyte',
      'Stitch Data',
    ],
  },
  {
    label: 'Data science',
    domains: ['data'],
    items: [
      'Feature Engineering',
      'Time Series Forecasting',
      'Predictive Modeling',
      'Bayesian Statistics',
      'Regression Analysis',
      'Classification',
      'Clustering',
      'Recommendation Systems',
      'Feature Store',
    ],
  },
  {
    label: 'QA and testing',
    domains: ['software'],
    items: [
      'Test Automation',
      'Contract Testing',
      'Mutation Testing',
      'Snapshot Testing',
      'Accessibility Testing',
      'Chaos Engineering',
      'Fuzz Testing',
      'API Testing',
      'Mobile Testing',
      'Browser Testing',
    ],
  },
  {
    label: 'Mobile',
    domains: ['software'],
    items: [
      'Firebase',
      'Crashlytics',
      'App Store Connect',
      'Google Play Console',
      'Mobile Analytics',
      'Push Notifications',
      'Mobile Security',
    ],
  },
  {
    label: 'IoT and embedded',
    domains: ['manufacturing'],
    items: [
      'Arduino',
      'Raspberry Pi',
      'ESP32',
      'MQTT',
      'LoRaWAN',
      'Zigbee',
      'BLE',
      'Industrial IoT',
    ],
  },
  {
    label: 'Blockchain',
    domains: ['software'],
    items: [
      'Ethereum',
      'Solana',
      'Hyperledger',
      'Smart Contracts',
      'Web3',
      'NFTs',
      'DeFi',
      'Solidity Development',
    ],
  },
  {
    label: 'Geospatial',
    domains: ['data'],
    items: [
      'ArcGIS',
      'QGIS',
      'GeoJSON',
      'Mapbox',
      'Google Maps Platform',
      'OpenStreetMap',
      'Spatial Analysis',
    ],
  },
  {
    label: 'ERP and CRM',
    domains: ['business'],
    items: [
      'SAP',
      'SAP S/4HANA',
      'Oracle ERP',
      'Microsoft Dynamics 365',
      'Zoho CRM',
      'Odoo',
      'NetSuite',
    ],
  },
  {
    label: 'Business intelligence',
    domains: ['data'],
    items: [
      'Qlik Sense',
      'QlikView',
      'IBM Cognos',
      'SAP BusinessObjects',
      'Oracle BI',
      'Sisense',
      'MicroStrategy',
      'ThoughtSpot',
    ],
  },
  {
    label: 'Digital marketing tools',
    domains: ['marketing'],
    items: [
      'Google Tag Manager',
      'Search Console',
      'Ahrefs',
      'SEMrush',
      'Moz',
      'Screaming Frog',
      'Hotjar',
      'Mixpanel',
      'Amplitude',
      'Firebase Analytics',
    ],
  },
  {
    label: 'E-commerce and payments',
    domains: ['retail'],
    items: [
      'Shopify',
      'Magento',
      'WooCommerce',
      'BigCommerce',
      'Stripe',
      'PayPal',
      'Razorpay',
      'Midtrans',
      'Xendit',
    ],
  },
  {
    label: 'Manufacturing and CAD',
    domains: ['manufacturing'],
    items: [
      'PLC Programming',
      'CNC Programming',
      'SCADA',
      'AutoCAD Electrical',
      'SolidWorks',
      'CATIA',
      'Siemens NX',
      'Quality Control',
    ],
  },
  {
    label: 'Finance systems',
    domains: ['finance'],
    items: [
      'IFRS',
      'GAAP',
      'SAP FICO',
      'Oracle Financial Cloud',
      'Treasury Management',
      'Investment Analysis',
    ],
  },
  {
    label: 'HR systems',
    domains: ['people'],
    items: [
      'Workday',
      'SAP SuccessFactors',
      'BambooHR',
      'Greenhouse ATS',
      'Lever ATS',
      'Performance Review',
      'Workforce Analytics',
    ],
  },
  {
    label: 'Healthcare systems',
    domains: ['healthcare'],
    items: [
      'Epic',
      'Cerner',
      'HL7',
      'FHIR',
      'PACS',
      'DICOM',
    ],
  },
  {
    label: 'Creative software',
    domains: ['design'],
    items: [
      'Adobe Lightroom',
      'Adobe Animate',
      'Adobe Audition',
      'Adobe Premiere Rush',
      'SketchUp',
      'Rhino',
      'Autodesk Maya',
      'Autodesk AutoCAD',
      'Figma Variables',
      'Design Tokens',
    ],
  },
  {
    label: 'Leadership',
    domains: ['general'],
    items: [
      'Visionary Leadership',
      'Servant Leadership',
      'Situational Leadership',
      'Executive Coaching',
      'Change Leadership',
      'Team Motivation',
      'Talent Development',
      'Succession Planning',
    ],
  },
  {
    label: 'Communication',
    domains: ['general'],
    items: [
      'Mediation',
      'Persuasive Communication',
      'Diplomacy',
      'Networking',
      'Facilitation',
      'Public Relations',
    ],
  },
  {
    label: 'Critical thinking',
    domains: ['general'],
    items: [
      'Systems Analysis',
      'Strategic Analysis',
      'Business Analysis',
      'Hypothesis Testing',
      'Scenario Planning',
      'Risk Analysis',
    ],
  },
  {
    label: 'Personal development',
    domains: ['general'],
    items: [
      'Self Reflection',
      'Self Discipline',
      'Self Awareness',
      'Confidence',
      'Adaptability',
      'Emotional Resilience',
      'Curiosity',
      'Learning Mindset',
    ],
  },
  {
    label: 'Collaboration',
    domains: ['general'],
    items: [
      'Cross-cultural Collaboration',
      'Stakeholder Alignment',
      'Consensus Building',
      'Relationship Management',
      'Peer Mentoring',
      'Team Facilitation',
    ],
  },
  {
    label: 'Customer focus',
    domains: ['success'],
    items: [
      'Customer Advocacy',
      'Customer Discovery',
      'Customer Interviewing',
      'Active Empathy',
      'Customer Education',
      'Customer Retention Strategy',
    ],
  },
  {
    label: 'Ways of working',
    domains: ['general'],
    items: [
      'Prioritization',
      'Workload Management',
      'Goal Execution',
      'Decision Prioritization',
      'Focus Management',
      'Meeting Facilitation',
    ],
  },
  {
    label: 'Innovation',
    domains: ['product'],
    items: [
      'Design Sprint',
      'Opportunity Identification',
      'Product Innovation',
      'Business Innovation',
      'Creative Problem Solving',
      'Entrepreneurial Thinking',
    ],
  },
  {
    label: 'Professionalism',
    domains: ['general'],
    items: [
      'Ethical Decision Making',
      'Integrity',
      'Confidentiality',
      'Accountability',
      'Reliability',
      'Professional Judgment',
    ],
  },
  {
    label: 'Working globally',
    domains: ['general'],
    items: [
      'Cultural Intelligence',
      'Diversity and Inclusion',
      'International Collaboration',
      'Remote Leadership',
      'Virtual Team Management',
      'Global Communication',
    ],
  },
  {
    label: 'Productivity tools',
    domains: ['general'],
    items: [
      'Microsoft Office',
      'Google Workspace',
      'Slack',
      'Microsoft Teams',
      'Zoom',
      'Airtable',
      'Coda',
      'Miro',
      'Lucidchart',
    ],
  },

]

/** Every value, in section order. The search path needs one flat list. */
export function flattenSections(sections: readonly Section[]): string[] {
  return sections.flatMap((section) => section.items)
}
